services:
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db
      - redis
    command: >
      bash -c "alembic upgrade head && gunicorn main:app --workers=4 --worker-class=uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"

  db:
    image: postgres:latest
    container_name: postgres_app
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_app
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
