version: '3.8'

services:
  app:
    image: kojiakbar2806/fastapi_app:latest  # Docker Hub-dan imidj
    container_name: fastapi
    ports:
      - "8000:8000"  # Hostdagi port:Container port
    env_file:
      - .env  # Muhit o'zgaruvchilari
    volumes:
      - .:/app  # Loyiha papkasini konteynerga ulash
    restart: always  # Konteynerni qayta ishga tushirish qoidalari
    depends_on:
      - db
      - redis
    command: >
      bash -c "alembic upgrade head && gunicorn main:app --workers=4 --worker-class=uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"

  db:
    image: postgres:latest  # Postgres imidji
    container_name: postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest  # Redis imidji
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
