name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            /root/.cache/docker
            /root/.cache/buildkit
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fasapit-docker:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fasapit-docker:latest

      # - name: Deploy to AWS EC2
      #   uses: appleboy/ssh-action@v0.1.5
      #   with:
      #     host: ${{ secrets.AWS_EC2_IP }}
      #     key: ${{ secrets.AWS_SSH_KEY }}
      #     username: ubuntu
      #     script: |
      #       echo "Connected successfully"
      #       cd /path/to/your/project
      #       docker-compose pull
      #       docker-compose up -d
