name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  test-ssh-connection:
    name: Test SSH Connection
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: SSH into Server and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_SSH_USERNAME }}@${{ secrets.AWS_SSH_HOST }} \
          "echo 'connected'"