name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        env:
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Test SSH connection
        env:
          SERVER_IP: ${{ secrets.AWS_SSH_HOST }}
          SERVER_USER: ${{ secrets.AWS_SSH_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} "echo 'SSH connection successful'"
