name: Push to Docker Hub and Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Restore pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fasapit-docker:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fasapit-docker:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fasapit-docker:cache,mode=max

      # - name: Deploy to AWS EC2
      #   env:
      #     AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
      #     AWS_EC2_IP: ${{ secrets.AWS_EC2_IP }}
      #   run: |
      #     chmod 600 $AWS_SSH_KEY
      #     ssh -i $AWS_SSH_KEY ubuntu@$AWS_EC2_IP << 'EOF'
      #       cd /path/to/your/project
      #       docker-compose pull
      #       docker-compose up -d --no-deps --build
      #     EOF
