name: Build and Deploy to AWS

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      APP_ENV: development
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment-specific .env file
        run: |
          if [ "${{ env.APP_ENV }}" == "development" ]; then
            echo "${{ secrets.ENV_FILE_CONTENT_DEV }}" > .env
          elif [ "${{ env.APP_ENV }}" == "production" ]; then
            echo "${{ secrets.ENV_FILE_CONTENT_PROD }}" > .env
          fi

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Build Docker Image
        run: |
          docker buildx build \
            --cache-to type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.CONTAINER_NAME }}-cache \
            --cache-from type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.CONTAINER_NAME }}-cache \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.CONTAINER_NAME }}:latest \
            --push .

      - name: Deploy to AWS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/fastapi-docker
            cd ~/fastapi-docker

            # Pull new Docker image
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.CONTAINER_NAME }}:latest

            # Check if container exists
            if sudo docker ps -a --format '{{.Names}}' | grep -q '^my_container$'; then
              sudo docker stop my_container || true
              sudo docker rm my_container || true
            fi

            # Run Docker container
            sudo docker run -d --name my_container --env-file .env ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.CONTAINER_NAME }}:latest

      - name: Save Docker Build Cache
        if: success() || failure()
        run: |
          docker buildx build \
            --cache-to type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.CONTAINER_NAME }}-cache \
            --push .
