name: Build and Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/${{ secrets.DOCKER_HUB_IMAGE }}:latest .
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/${{ secrets.DOCKER_HUB_IMAGE }}:latest

      - name: Deploy to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
          HOST: ${{ secrets.AWS_SSH_HOST }}
          USERNAME: ${{ secrets.AWS_SSH_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i "private_key.pem" "$USERNAME@$HOST" << 'EOF'
            cd ~/fastapi-docker
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_IMAGE }}:latest
            sudo docker compose up -d --build

            rm -rf private_key.pem
          EOF
